# Generated by Django 5.2.7 on 2025-10-06 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_developerratings'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_ratings', to=settings.AUTH_USER_MODEL)),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
