# Generated by Django 5.2.7 on 2025-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_developerratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
