# Generated by Django 5.2.7 on 2025-12-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_developer_behance_url_developer_github_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="avg_projects_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3
            ),
        ),
    ]
