# Generated by Django 5.2.6 on 2025-09-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='deploy_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='development_stage',
            field=models.CharField(choices=[('initiation', 'Project Initiation'), ('planning', 'Planning'), ('design', 'Design & Architecture'), ('implementation', 'Implementation / Development'), ('testing', 'Testing & QA'), ('completed', 'Completed'), ('deployed', 'Deployed')], default='backend', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('DEV', 'Developer'), ('LEAD', 'Team Lead'), ('PM', 'Project Manager'), ('Mentor', 'Mentor')], default='DEV', max_length=10),
        ),
    ]
