# Generated by Django 5.2.7 on 2025-10-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_edit_project_perm_projectmembership_edit_project_info_perm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrating',
            old_name='user_added',
            new_name='rated_by',
        ),
    ]
