# Generated by Django 5.2.7 on 2025-10-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_user_added_projectrating_rated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
