# Generated by Django 5.2.7 on 2025-10-07 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project'),
        ),
    ]
