# Generated by Django 5.2.6 on 2025-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_developerratings_created_at_developerratings_project_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='domen',
            field=models.CharField(choices=[('initiation', 'Project Initiation'), ('planning', 'Planning'), ('design', 'Design & Architecture'), ('implementation', 'Implementation / Development'), ('testing', 'Testing & QA'), ('completed', 'Completed'), ('deployed', 'Deployed')], default='backend', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='development_stage',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('blockchain', 'Blockchain'), ('food_tech', 'Food Tech'), ('technology', 'Technology'), ('e_commerce', 'E-Commerce'), ('ed_tech', 'EdTech'), ('utilities', 'Utilities'), ('design', 'Design'), ('saas', 'SaaS'), ('fintech', 'FinTech'), ('ml', 'Machine Learning'), ('big_data', 'Big Data')], default='backend', max_length=50),
        ),
    ]
