# Generated by Django 5.2.7 on 2025-10-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_development_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectapplication",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="projects.projectopenrole",
            ),
        ),
    ]
