# Generated by Django 5.2.6 on 2025-10-01 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectrating_unique_together_project_domen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='open_to_candidates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='unical_id',
            field=models.CharField(default='unical_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='development_stage',
            field=models.CharField(choices=[('initiation', 'Project Initiation'), ('planning', 'Planning'), ('design', 'Design & Architecture'), ('implementation', 'Implementation / Development'), ('testing', 'Testing & QA'), ('completed', 'Completed'), ('deployed', 'Deployed')], default='backend', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='domen',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('blockchain', 'Blockchain'), ('food_tech', 'Food Tech'), ('technology', 'Technology'), ('e_commerce', 'E-Commerce'), ('ed_tech', 'EdTech'), ('utilities', 'Utilities'), ('design', 'Design'), ('saas', 'SaaS'), ('fintech', 'FinTech'), ('ml', 'Machine Learning'), ('big_data', 'Big Data')], default='backend', max_length=50),
        ),
        migrations.CreateModel(
            name='NewCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
