# Generated by Django 5.2.6 on 2025-10-04 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_open_to_candidates_project_unical_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='domen',
            new_name='domain',
        ),
        migrations.AlterField(
            model_name='project',
            name='development_stage',
            field=models.CharField(choices=[('initiation', 'Project Initiation'), ('planning', 'Planning'), ('design', 'Design & Architecture'), ('implementation', 'Implementation / Development'), ('testing', 'Testing & QA'), ('deployed', 'Deployed')], default='backend', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('DEV', 'Developer'), ('LEAD', 'Team Lead'), ('PM', 'Project Manager'), ('Mentor', 'Mentor')], default='DEV', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOpenRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_roles', to='projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='NewCandidates',
        ),
    ]
