# Generated by Django 5.2.6 on 2025-10-04 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_domen_project_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectopenrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectopenrole',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
