# Generated by Django 5.2.6 on 2025-10-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectopenrole_created_at_projectopenrole_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrating',
            name='user',
        ),
    ]
