# Generated by Django 5.2.7 on 2025-11-16 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_unical_id_project_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uuid',
        ),
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False, null=True),
        ),
    ]
