# Generated by Django 5.2.7 on 2025-11-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_remove_project_uuid_project_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="field",
            new_name="uuid",
        ),
    ]
